Repository flexera-public/flexera-plugins, pull requests merged in 2018-05, with the labels that each got.

#152 rs_azure_compute: Add new methods for virtualmachine resource
  azure/rs_azure_compute/README.md
  azure/rs_azure_compute/azure_compute_plugin.rb
  azure/rs_azure_compute/changelog.md
Labels: READY-FOR-REVIEW, enhancement

#156 Psasset 841
  azure/rs_azure_compute/changelog.md
  azure/rs_azure_compute/compute_test_cat.rb
Labels: repo_maintenance

#158 AWS CloudFront Plugin - Initial Release
  README.md
  aws/rs_aws_cloudfront/README.md
  aws/rs_aws_cloudfront/aws_cloudfront_plugin.rb
  aws/rs_aws_cloudfront/changelog.md
  aws/rs_aws_cloudfront/cloudfront_test_cat.rb
Labels: READY-FOR-REVIEW

#160 Digital Ocean - Initial Release
  README.md
  digital_ocean/README.md
  digital_ocean/changelog.md
  digital_ocean/digital_ocean_test_cat.rb
  digital_ocean/rs_do_plugin.rb
Labels: READY-FOR-REVIEW

#107 Route 53
  README.md
  aws/rs_aws_route53/README.md
  aws/rs_aws_route53/aws_route53_plugin.rb
  aws/rs_aws_route53/changelog.md
  aws/rs_aws_route53/route53_test_cat.rb
Labels: READY-FOR-REVIEW

#161 Release Week of 05-07-2018
  CHANGELOG.md
Labels: READY-FOR-REVIEW, changelog
