Repository flexera-public/flexera-plugins, pull requests merged in 2022-01, with the labels that each got.

#225 adding github actions
  .github/workflows/testing-plugins.yml
  .travis.yml
Labels: READY-FOR-REVIEW

#224 UI 3703
  .github/workflows/testing-plugins.yml
  aws/rs_aws_compute/README.md
  aws/rs_aws_compute/aws_compute_plugin.rb
  aws/rs_aws_compute/changelog.md
  aws/rs_aws_compute/compute_instance_test_cat.rb
  aws/rs_aws_compute/two_credentials.rb
  azure/rs_azure_compute/README.md
  azure/rs_azure_compute/azure_compute_plugin.rb
  azure/rs_azure_compute/changelog.md
Labels: READY-FOR-REVIEW

#204 POL-334 Azure Blob Service
  .gitignore
  .textlintrc
  .vscode/settings.json
  README.md
  azure/rs_azure_blob_service/README.md
  azure/rs_azure_blob_service/azure_blob_services.rb
  azure/rs_azure_blob_service/changelog.md
  package-lock.json
  package.json
Labels: READY-FOR-REVIEW, changelog

#199 POL-303 - AWS RDS resource browser changes
  aws/rs_aws_rds/aws_rds.plugin
  aws/rs_aws_rds/changelog.md
  aws/rs_aws_rds/rds_test_cat.rb
Labels: enhancement, READY-FOR-REVIEW, changelog

#201 POL-335-Google-Cloud-Storage
  README.md
  google/google_cloud_storage/README.md
  google/google_cloud_storage/changelog.md
  google/google_cloud_storage/google_cloud_storage.rb
Labels: READY-FOR-REVIEW, changelog

#184 POL-198 - Azure AKS Plugin
  azure/rs_azure_aks/CHANGELOG.md
  azure/rs_azure_aks/README.md
  azure/rs_azure_aks/azure_aks.plugin
  azure/rs_azure_aks/azure_aks_plugin.rb
  azure/rs_azure_aks/azure_aks_test_cat.rb
Labels: READY-FOR-REVIEW, 2.0

#186 POL-199 - GKE Plugin
  google/gke/CHANGELOG.md
  google/gke/gke.rb
  google/gke/gke_test_cat.rb
Labels: READY-FOR-REVIEW, 2.0

#181 POL-197 - AWS EKS
  aws/rs_aws_eks/README.md
  aws/rs_aws_eks/aws_eks_plugin.plugin
  aws/rs_aws_eks/aws_eks_plugin.rb
  aws/rs_aws_eks/changelog.md
  aws/rs_aws_eks/eks_test_cat.rb
Labels: READY-FOR-REVIEW, 2.0
